CREATE TABLE table1 (a STRING CONSTRAINT d1 DEFAULT 'key', b STRING );
DESCRIBE FORMATTED table1;

ALTER TABLE table1 DROP CONSTRAINT d1;
DESC FORMATTED table1;

ALTER TABLE table1 CHANGE b b STRING DEFAULT "value" ;
DESC FORMATTED table1;

--DROP COLUMN
--ADD COLUMN
